<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Quieres recibir las ltimas novedades y las ofertas ms ardientesS, me interesaPor ahora no</name>
   <tag></tag>
   <elementGuidId>66dfed30-5e7a-4104-a336-af6b2493af63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onesignal-slidedown-dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#onesignal-slidedown-dialog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c41544d-5d61-403c-ac02-6af7ec68fdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onesignal-slidedown-dialog</value>
      <webElementGuid>98c42524-d481-4755-82d3-f7e5d4ba4e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onesignal-slidedown-dialog</value>
      <webElementGuid>a1400220-2333-40dd-8001-020e5478f3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¿Quieres recibir las últimas novedades y las ofertas más ardientes?Sí, me interesaPor ahora no</value>
      <webElementGuid>9c835b68-3568-4806-8562-e2cc88534c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onesignal-slidedown-dialog&quot;)</value>
      <webElementGuid>b019aacd-7142-4209-b9fe-04b29a04efda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='onesignal-slidedown-dialog']</value>
      <webElementGuid>9acca0a9-5a10-4625-890a-87f12f857f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onesignal-slidedown-container']/div</value>
      <webElementGuid>00cbef3a-c917-4c15-923f-26f21d175dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[3]</value>
      <webElementGuid>0b79a901-902f-439a-8bbc-eaf4c36e43e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'onesignal-slidedown-dialog', '&quot;', ')')])[1]/following::div[9]</value>
      <webElementGuid>505b39b3-766f-43f3-b160-68c1165a4151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div</value>
      <webElementGuid>37dc2765-9cd4-4ed7-9cf8-425d44370cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'onesignal-slidedown-dialog' and (text() = '¿Quieres recibir las últimas novedades y las ofertas más ardientes?Sí, me interesaPor ahora no' or . = '¿Quieres recibir las últimas novedades y las ofertas más ardientes?Sí, me interesaPor ahora no')]</value>
      <webElementGuid>6a71180a-b9c8-4558-8928-633bcf7a8fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
