<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , dy-email, , ))_promotio_e0d49f</name>
   <tag></tag>
   <elementGuidId>9b0ce1ff-f1d9-4953-aee1-e6a8814d2e38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dy-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dy-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0dd7b6e1-c0e6-4bf5-916a-0174ad60b463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dy-email</value>
      <webElementGuid>078b0b7e-e3d0-4756-a9a4-c4ec433d51ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bdb261a2-06b6-48cf-87b6-d0d884222fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>promotional_newsletter_form[email]</value>
      <webElementGuid>2f5cd373-7c3b-4eb9-acad-c95629cd2a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Suscríbete con tu email</value>
      <webElementGuid>6998ead5-b588-482a-82f3-8484f8b018a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-xs</value>
      <webElementGuid>a489e46a-89a9-4392-a5fa-5d7f960b80bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dy-email&quot;)</value>
      <webElementGuid>a07606ee-4ad8-4ab6-9f80-048feb80b3ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dy-email']</value>
      <webElementGuid>1b9ba973-ad1b-4186-91f2-ab6e0c0c2bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dy-newsltpopup']/form/div/div/input</value>
      <webElementGuid>0a557e12-5bd8-4449-be2b-9e792212c3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div/input</value>
      <webElementGuid>cd646eef-7520-40f3-b2ff-1c9f9c41ba81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dy-email' and @type = 'email' and @name = 'promotional_newsletter_form[email]' and @placeholder = 'Suscríbete con tu email']</value>
      <webElementGuid>6d0a1eda-4b96-48b3-bbaa-45e55522b1d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
