<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Declaro que he ledo y autorizo el uso_b41df4</name>
   <tag></tag>
   <elementGuidId>e4467c88-6059-4e31-8bd9-5aee5e7ca1ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-12 > div.checkbox > label > #terms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='terms'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e99c007-88a3-437f-8d57-6517534df8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>b7ca4366-8921-4e9d-8a81-2fa500db21f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9de65261-be8c-40ca-8830-57a3b46df9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dy-newsltpopup&quot;)/form[@class=&quot;dy-newsltpopup-form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;checkbox&quot;]/label[1]/input[@id=&quot;terms&quot;]</value>
      <webElementGuid>044e7b9e-0085-4974-9bee-555d8867ee66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='terms'])[2]</value>
      <webElementGuid>18d68b64-719c-4975-a222-d2c4522b278f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dy-newsltpopup']/form/div/div/div/label/input</value>
      <webElementGuid>71024930-ff2f-4d30-9df8-a0ee092706a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/label/input</value>
      <webElementGuid>a71d320e-668b-4ec4-b069-5700bec9a104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'terms' and @type = 'checkbox']</value>
      <webElementGuid>ef42f067-1ee6-4870-9a34-6ec468440e82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
