<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_detail_title</name>
   <tag></tag>
   <elementGuidId>98defd75-6ff4-4d80-8d0a-290db891ca36</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.product-name</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='display-zoom']/div/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1e133748-9ba6-493c-8942-57027e272e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>fdd78550-7c4c-4199-8734-9add6d0092eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>10da9c84-6dde-4d46-ac9a-69a8096aad7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Portátil LENOVO V15 IGL INTEL CELERON N4020 8GB 256GB SSD 15,6 HD FREEDOS</value>
      <webElementGuid>2c82de77-1954-4ab9-8473-b89d64c47cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display-zoom&quot;)/div[@class=&quot;product-title&quot;]/h1[@class=&quot;col-12 product-title-box&quot;]/span[@class=&quot;product-name&quot;]</value>
      <webElementGuid>03c2cd49-8ff2-4d49-a4d8-034aaf52a988</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='display-zoom']/div/h1/span</value>
      <webElementGuid>cc076ba9-4870-4b31-b420-a7af1917a5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portátil LENOVO V15 IGL INTEL CELERON N4020 8GB 256GB SSD 15,6 HD FREEDOS'])[1]/following::span[2]</value>
      <webElementGuid>08570cb8-954a-4430-91c6-6dc2c68f52db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptops'])[1]/following::span[3]</value>
      <webElementGuid>7edda807-b0ef-4375-954f-2c0c1a1d7ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lenovo'])[7]/preceding::span[1]</value>
      <webElementGuid>cadf478e-19e1-439d-a87e-8083f1296484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>824f2ab6-c4e2-4c64-83a4-2d746e77847f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Portátil LENOVO V15 IGL INTEL CELERON N4020 8GB 256GB SSD 15,6 HD FREEDOS' or . = 'Portátil LENOVO V15 IGL INTEL CELERON N4020 8GB 256GB SSD 15,6 HD FREEDOS')]</value>
      <webElementGuid>0161a2ef-bee2-48d3-809f-087ad539f3c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
