<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_detail_title</name>
   <tag></tag>
   <elementGuidId>98defd75-6ff4-4d80-8d0a-290db891ca36</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.product-name</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='product-name']/div/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8687d108-5e6e-45ee-ab16-66a899e47b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>c93a7374-eccc-4dfc-971f-e291f8a6e845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>6999c837-3c79-435d-b20c-bd8f7c63fe3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Portátil LENOVO V15 IGL INTEL CELERON N4020 8GB 256GB SSD 15,6 HD FREEDOS</value>
      <webElementGuid>ca9182ac-74e0-4c84-ae1b-e1909a93dd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display-zoom&quot;)/div[@class=&quot;product-title&quot;]/h1[@class=&quot;col-12 product-title-box&quot;]/span[@class=&quot;product-name&quot;]</value>
      <webElementGuid>b62df086-c489-4b83-b8e7-38fafdb5026d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='display-zoom']/div/h1/span</value>
      <webElementGuid>2d8f4c2a-ed1e-450a-acfd-f905255662f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portátil LENOVO V15 IGL INTEL CELERON N4020 8GB 256GB SSD 15,6 HD FREEDOS'])[1]/following::span[2]</value>
      <webElementGuid>8d670310-4a29-47df-bae6-6ccc906e6d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptops'])[1]/following::span[3]</value>
      <webElementGuid>eb28e561-90cf-4eeb-bbb8-ff3f7c94aba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lenovo'])[7]/preceding::span[1]</value>
      <webElementGuid>dfb305e9-cbe4-442b-8dc4-541d801b3e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>6c602bc5-9b67-472f-8a17-67272bc3ad1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Portátil LENOVO V15 IGL INTEL CELERON N4020 8GB 256GB SSD 15,6 HD FREEDOS' or . = 'Portátil LENOVO V15 IGL INTEL CELERON N4020 8GB 256GB SSD 15,6 HD FREEDOS')]</value>
      <webElementGuid>a731c37c-5fb3-478e-a170-21a70a243db1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
