<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jon steven</name>
   <tag></tag>
   <elementGuidId>6222c9b0-6915-4b12-9ede-13f99c48de7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-profile-user-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='header-profile-user-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a47c9b60-2a40-4fa4-a626-dbed691ed670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>eacefe6d-fd2d-454a-85d8-7f0e78ff89c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-profile-user-name</value>
      <webElementGuid>02065af4-e790-494f-9cc5-6183c576b0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jon steven</value>
      <webElementGuid>26005cd8-879d-4db8-9ca1-c9e5d30554d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-profile-user-name&quot;)</value>
      <webElementGuid>0789fac8-88e9-4df2-b9f7-61d70158c5f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='header-profile-user-name']</value>
      <webElementGuid>1c748873-83b5-4ea3-8737-a1eb73024e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/div/div[4]/div[2]/a/span[2]</value>
      <webElementGuid>ddf96b43-b979-447e-85d7-965acf8e98b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis pedidos'])[1]/preceding::span[2]</value>
      <webElementGuid>d7d74c01-baad-46ad-a5b7-a7935f602cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrito'])[1]/preceding::span[4]</value>
      <webElementGuid>4b1c1a52-f4d8-44fb-b564-2567ed615707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jon steven']/parent::*</value>
      <webElementGuid>0d3c602b-7b87-4d1a-9fbd-e2dc3c6a2ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>9754ce25-1dac-49ef-937a-a473bdafa81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'header-profile-user-name' and (text() = 'Jon steven' or . = 'Jon steven')]</value>
      <webElementGuid>d35adf1b-e0e8-4e37-8fa0-59e17e2bb210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
