<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione un MunicpioArmeniaBuenavi_7ca3fc</name>
   <tag></tag>
   <elementGuidId>ce429b38-7394-43f6-b3e3-d2dc05f717c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart_shipping_address_municipality</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cart_shipping_address_municipality']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3a87e112-9dd3-4eab-9a5f-fc9df9487bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart_shipping_address_municipality</value>
      <webElementGuid>a137ab54-438b-429c-b987-83c69b4bed12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart_shipping_address[municipality]</value>
      <webElementGuid>679da322-fb65-47ff-8f11-57e99f007087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>42c0c2ad-6d18-4f5b-b2ec-c25b73340641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>addressForm.input.municipality</value>
      <webElementGuid>b54e771b-5294-4aed-954b-7a096a73bc4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>municipality.id as municipality.name for municipality in addressForm.municipalities track by municipality.id</value>
      <webElementGuid>a66bca3c-a0d2-4004-9eee-1e35da420418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-level2</value>
      <webElementGuid>fe7a03c5-bbc6-4302-bb2e-35606c1a429d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>containerclass</name>
      <type>Main</type>
      <value>col-md-12</value>
      <webElementGuid>39d77a7b-7371-49c5-9125-4a424e3174ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>479bd602-4b89-4d94-95a7-ac422d22e790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione un MunicípioArmeniaBuenavistaCalarcaCircasiaCordobaFilandiaGenovaLa TebaidaMontenegroPijaoQuimbayaSalento</value>
      <webElementGuid>a533757b-21f8-4c83-a688-d3522f2d0747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart_shipping_address_municipality&quot;)</value>
      <webElementGuid>e44a60c0-6a09-4525-b111-48e556d197d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cart_shipping_address_municipality']</value>
      <webElementGuid>b5565c12-f185-4fcc-8021-e9ecb678928c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[1]/following::select[1]</value>
      <webElementGuid>19b2bac9-4a9f-4647-9d47-fc285f72141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento'])[1]/following::select[2]</value>
      <webElementGuid>503fa3e3-b042-4992-b837-340560d33c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calcular'])[1]/preceding::select[1]</value>
      <webElementGuid>fea09a7c-c1df-476c-8f26-69c32fb5be75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aplicar cupón'])[1]/preceding::select[1]</value>
      <webElementGuid>b022df5b-0e0c-4a28-9f48-4a11f0d16dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/select</value>
      <webElementGuid>c6a7415c-09d0-4f87-aea7-0d354d73ba96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cart_shipping_address_municipality' and @name = 'cart_shipping_address[municipality]' and (text() = 'Seleccione un MunicípioArmeniaBuenavistaCalarcaCircasiaCordobaFilandiaGenovaLa TebaidaMontenegroPijaoQuimbayaSalento' or . = 'Seleccione un MunicípioArmeniaBuenavistaCalarcaCircasiaCordobaFilandiaGenovaLa TebaidaMontenegroPijaoQuimbayaSalento')]</value>
      <webElementGuid>706e7168-36b7-4d38-b667-35e620e4eed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
