<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione un DepartamentoAmazonasAn_208eca</name>
   <tag></tag>
   <elementGuidId>62fe7268-f0be-4491-bfb0-3d8694e6e670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart_shipping_address_region</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cart_shipping_address_region']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a3f36500-8dd3-43f7-86f8-a3bba9ceedb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart_shipping_address_region</value>
      <webElementGuid>35838977-f5db-4ab4-af2a-9f710de3d096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart_shipping_address[region]</value>
      <webElementGuid>5b6b59f9-cb94-410a-888b-9eabe58c4c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>a8fc8d25-b1c4-4c91-bb79-8c3d0715e19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>addressForm.input.region</value>
      <webElementGuid>f99a039f-19cc-4e68-abd5-2756664c8b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>addressForm.loadMunicipalities()</value>
      <webElementGuid>bdb00942-170a-42c2-b7a3-fa56e75496d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-level1</value>
      <webElementGuid>e034f2f0-b993-47a3-9cd4-707652eb4470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>containerclass</name>
      <type>Main</type>
      <value>col-md-12</value>
      <webElementGuid>5670d733-81a0-4459-bbcc-4decd5c708ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>d99ba9a1-a413-4448-b5b1-063eadcaecb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione un DepartamentoAmazonasAntioquiaAraucaArchipielago De San AndresAtlanticoBogota D.CBolivarBoyacaCaldasCaquetaCasanareCaucaCesarChocoCordobaCundinamarcaGuainiaGuaviareHuilaLa GuajiraMagdalenaMetaNariñoNorte De SantanderPutumayoQuindioRisaraldaSantanderSucreTolimaValle Del CaucaVaupesVichada</value>
      <webElementGuid>ba927a8a-cc9c-42f3-9aeb-e26f82052701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart_shipping_address_region&quot;)</value>
      <webElementGuid>f495d9b3-1c14-441f-80bd-8629c8d03092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cart_shipping_address_region']</value>
      <webElementGuid>b0b123d4-b5e3-4c0e-9560-21a52129a3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento'])[1]/following::select[1]</value>
      <webElementGuid>ca0ceaf8-3edd-45f7-a6a8-44b7beb2c659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calcular envío'])[1]/following::select[1]</value>
      <webElementGuid>f47c54a8-6466-4178-8090-7bf96577cc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Município'])[1]/preceding::select[1]</value>
      <webElementGuid>5ae69ebd-e4ed-45ba-b84f-698166a2f13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calcular'])[1]/preceding::select[2]</value>
      <webElementGuid>06e4d6f8-4b6f-49ce-a437-cd066e2de3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/select</value>
      <webElementGuid>b0f7703c-52ca-4e84-9ae5-fe1a173dd2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cart_shipping_address_region' and @name = 'cart_shipping_address[region]' and (text() = 'Seleccione un DepartamentoAmazonasAntioquiaAraucaArchipielago De San AndresAtlanticoBogota D.CBolivarBoyacaCaldasCaquetaCasanareCaucaCesarChocoCordobaCundinamarcaGuainiaGuaviareHuilaLa GuajiraMagdalenaMetaNariñoNorte De SantanderPutumayoQuindioRisaraldaSantanderSucreTolimaValle Del CaucaVaupesVichada' or . = 'Seleccione un DepartamentoAmazonasAntioquiaAraucaArchipielago De San AndresAtlanticoBogota D.CBolivarBoyacaCaldasCaquetaCasanareCaucaCesarChocoCordobaCundinamarcaGuainiaGuaviareHuilaLa GuajiraMagdalenaMetaNariñoNorte De SantanderPutumayoQuindioRisaraldaSantanderSucreTolimaValle Del CaucaVaupesVichada')]</value>
      <webElementGuid>0f2943c5-c131-4576-8556-f1824fec0aec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
