<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_iPhone 11 64GB Purpura Purple Seminuevo</name>
   <tag></tag>
   <elementGuidId>449dffcd-d024-4c35-9db9-be90097a7dc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.title-section</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='catalogue-product-container']/div/a/div[2]/p/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84ad0e06-b0d5-4397-a676-f8b18756791a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-section</value>
      <webElementGuid>3bab9937-d998-48d0-bfbc-db39194ecc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iPhone 11 64GB Purpura Purple Seminuevo</value>
      <webElementGuid>c761f9e7-fd44-4bb5-a11f-0e1bfeb6f860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catalogue-product-container&quot;)/div[@class=&quot;catalogue-product row&quot;]/a[@class=&quot;col-12 pl-0 pr-0&quot;]/div[@class=&quot;detail-container&quot;]/p[1]/span[@class=&quot;title-section&quot;]</value>
      <webElementGuid>a7d0999e-18f7-4230-8887-a1faefdb4e03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catalogue-product-container']/div/a/div[2]/p/span</value>
      <webElementGuid>868d0d0a-1093-45d1-9ea4-a67411d9e6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envío gratis'])[2]/following::span[1]</value>
      <webElementGuid>9892ee2d-f50d-43b6-8d9b-7606c37e3329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envío gratis'])[1]/following::span[1]</value>
      <webElementGuid>75028bbf-c189-4911-9599-d4419ee84650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2.899.900'])[1]/preceding::span[1]</value>
      <webElementGuid>136f7fd2-59c5-4b4a-b1ba-604296d37a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- 31%'])[1]/preceding::span[2]</value>
      <webElementGuid>12553a0c-14cb-4cfa-babc-012692c0f36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='iPhone 11 64GB Purpura Purple Seminuevo']/parent::*</value>
      <webElementGuid>bb79284b-f69d-4824-b3fa-203975ee65ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/p/span</value>
      <webElementGuid>6ea2a4c4-904d-4af1-b1f7-b31f7920f486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'iPhone 11 64GB Purpura Purple Seminuevo' or . = 'iPhone 11 64GB Purpura Purple Seminuevo')]</value>
      <webElementGuid>569d2553-4e72-4b01-b10b-a7f1a4251b72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
